plugins {
    alias(libs.plugins.android.library)
}
apply from: "../../common.gradle"
apply from: "../../playFlavor.gradle"

android {
    namespace "de.danoeh.antennapod.net.contentcrunch"
}

dependencies {
    implementation project(':model')
    implementation project(':net:common')
    implementation libs.androidx.security.crypto
    implementation libs.okhttp
    testImplementation libs.junit
    testImplementation libs.json
    testImplementation libs.mockwebserver
}
